@startuml
left to right direction


:Jugador: << Gamer >> as Player #green;line:green;line.bold;text:green
actor Administrador as Admin

Admin -left-|> Player

rectangle "Sistema de Compra de Skins" {
    (Comprar Skin) as CSkins
    usecase "Seleccionar Mètode de Pagament" as SMPagament
    usecase "Aplicar Descompte" as ADescompte
    usecase "Gestionar Inventari" as GestInv
    usecase "Reemborsar Compra" as Reemborsar
}



Player --> CSkins #green
Admin --> GestInv
Admin --> Reemborsar

CSkins .> SMPagament : <<include>>
CSkins <. ADescompte : <<extend>>
Reemborsar .> CSkins : <<extend>>
@enduml
